name: advds
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - scipy
  - scikit-learn
  - statsmodels
  - plotly
  - jupyterlab
  - ipykernel
  - notebook
  - pyarrow
  - requests
  - pyyaml
  - pip
  - pip:
      - yfinance
      - pandas-market-calendars
      - exchange-calendars
